### ISSUE TITLE
Avisor will fail to run on newer versions of dependencies

### ISSUE THREAD

**Issue by bettermultiply** [TenonOS/libos-summer-camp-workbench#1]
Hello, I get some trouble when test Avisor. When I run `make qemu`, avisor will stuck at `sp_elx_sync()`. You can see my  Linux version and tools version below.

![Garuda](https://github.com/TenonOS/libos-summer-camp-workbench/assets/98676202/347c712f-d7ea-45b1-b885-704006a373a2)

However, when I test in `Ubuntu 22.04.4 LTS x86_64`,  it just works well.

![Ubuntu](https://github.com/TenonOS/libos-summer-camp-workbench/assets/98676202/08045fd6-d192-44e3-9e7e-a5fef161f0a0)

Although I find the solution to deal with the case, to lower my toolchain version, I can't figure out the root reason and real ways to solve the error, I mean fix Avisor, could you give me some help? Thank you!

**Comment by MaiM1ng** [comment]
抱歉，由于时间仓促，这是我们的疏忽。如果作为题目发布，不应该因为工具链版本而影响题目本身。
至于这个问题，我先尝试复现一下。既然已经用其他方法规避了这个问题，可以先考虑完成题目。
avisor仅作为一个unikernel-guest hypervisor原型，仅用作学习与教学，难免出现差错，希望能够理解！

**Comment by bettermultiply** [comment]
嗯嗯，我只是在其他玩其它题目的时候遇到了类似的问题，一直很想知道原因(以及给 qemu issue/pr 的机会x)，但之前没有地方提问，这次正好有机会。如果您忙就不麻烦您仅仅因为我的求知欲浪费时间解答了，感谢回复

**Comment by MaiM1ng** [comment]
@bettermultiply 我在`Ubuntu 22.04.4 LTS x86_64`上使用`qemu 9.0.1`复现了该错误。
发现`ESR_EL2`的值为0X96000021，可以定位到这是一次内存写入错误，具体原因为`Address size fault, level 1`.
可以参考: [ARMv8 ESR_EL2](https://developer.arm.com/documentation/ddi0595/2020-12/AArch64-Registers/ESR-EL2--Exception-Syndrome-Register--EL2-?lang=en#fieldset_0-25_25)
可能的原因是QEMU在后续版本上某些行为和老版本有所不同，我不清楚是因为什么改动引入的。如果你感兴趣的话，可以尝试探索一下，探索的结果可以写入最终的验收报告中，这个仓库并不是avisor的源码仓库，因此就不需要提pr修复了
